apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
spec:
  selector:
    app: simple-calculator
  ports:
    - protocol: TCP
      port: 9090  # Exposed port
      targetPort: 9090  # Container's port
  type: LoadBalancer
